name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Day02
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make googletest lcov
          cd /usr/src/googletest
          sudo cmake -Bbuild -H.
          sudo cmake --build build --target install
          cd /usr/local/bin
          wget https://raw.github.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py

      - name: Configure CMake
        run: |
          mkdir -p day02/build
          cd day02/build
          cmake ..

      - name: Build
        run: |
          cd day02/build
          make clean && make

      - name: Run Unit Tests
        run: |
          cd day02/build
          ctest --output-on-failure -R unit_tests

      - name: Run Integration Tests
        run: |
          cd day02/build
          ctest --output-on-failure -R integration_tests

      - name: Run End-to-End Tests
        run: |
          cd day02/build
          ctest --output-on-failure -R end_to_end_tests

      - name: Generate code coverage
        run: |
          # There seems to be a bug in gcov that will misreport some block ends.
          # At the moment this only happens in test code, so we ignore the mismatch.
          lcov --rc lcov_branch_coverage=1 --rc geninfo_all_blocks=1 --directory day02 --capture --output-file coverage.info --ignore-errors mismatch
          lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage_filtered.info
          genhtml coverage_filtered.info --output-directory coverage_report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report

      - name: Convert LCOV to Cobertura
        run: python /usr/local/bin/lcov_cobertura.py coverage_filtered.info --output coverage.cobertura.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
